---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 3aab1253eb81fdc3fe4742eb3e4282a9ca43c6b7
    app.quarkus.io/build-timestamp: 2022-06-22 - 19:07:45 +0000
  labels:
    app.kubernetes.io/name: camel-quarkus-ws-to-event
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: camel-quarkus-ws-to-event
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: camel-quarkus-ws-to-event
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 3aab1253eb81fdc3fe4742eb3e4282a9ca43c6b7
    app.quarkus.io/build-timestamp: 2022-06-22 - 19:07:45 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: camel-quarkus-ws-to-event
    app.openshift.io/runtime: quarkus
  name: camel-quarkus-ws-to-event
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openjdk-11
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-11
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 3aab1253eb81fdc3fe4742eb3e4282a9ca43c6b7
    app.quarkus.io/build-timestamp: 2022-06-22 - 19:07:45 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: camel-quarkus-ws-to-event
    app.openshift.io/runtime: quarkus
  name: camel-quarkus-ws-to-event
spec:
  output:
    to:
      kind: ImageStreamTag
      name: camel-quarkus-ws-to-event:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11:latest
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 3aab1253eb81fdc3fe4742eb3e4282a9ca43c6b7
    app.quarkus.io/build-timestamp: 2022-06-22 - 19:07:45 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: camel-quarkus-ws-to-event
    app.openshift.io/runtime: quarkus
  name: camel-quarkus-ws-to-event
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: camel-quarkus-ws-to-event
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/commit-id: 3aab1253eb81fdc3fe4742eb3e4282a9ca43c6b7
        app.quarkus.io/build-timestamp: 2022-06-22 - 19:07:45 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: camel-quarkus-ws-to-event
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_ARTEMIS_URL
              value: tcp://ex-aao-hdls-svc:61616
            - name: KAFKA_GROUP_ID
              value: chatBotConsumerGroup
            - name: QUARKUS_ARTEMIS_DESTINATIONTYPE
              value: topic
            - name: QUARKUS_ARTEMIS_DESTINATIONNAME_PROCESSED
              value: chat-bot-processed
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap.horus.svc.cluster.local:9092
            - name: QUARKUS_ARTEMIS_DESTINATIONNAME_RAW
              value: chat-bot-raw
            - name: KAFKA_TOPIC_PROCESSED
              value: chat-bot-processed
            - name: QUARKUS_ARTEMIS_PASSWORD
              value: "123456"
            - name: KAFKA_TOPIC_RAW
              value: chat-bot-raw
            - name: QUARKUS_ARTEMIS_USERNAME
              value: admin
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: omelo/camel-quarkus-ws-to-event:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: camel-quarkus-ws-to-event
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - camel-quarkus-ws-to-event
        from:
          kind: ImageStreamTag
          name: camel-quarkus-ws-to-event:1.0.0-SNAPSHOT
      type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 3aab1253eb81fdc3fe4742eb3e4282a9ca43c6b7
    app.quarkus.io/build-timestamp: 2022-06-22 - 19:07:45 +0000
  labels:
    app.kubernetes.io/name: camel-quarkus-ws-to-event
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: camel-quarkus-ws-to-event
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: camel-quarkus-ws-to-event
